### ISSUE TITLE
Runtime exception from Atom

### ISSUE THREAD

**Issue by darkoverlordofdata** [inkytonik/atom-sbt#11]
sbt works perfectly from a separate command window.  But when I use this plugin, I get an error (see below). It says ANDROID_HOME is not set, yet is is, and other android tools are working. 
It says to 'run 'android update project -p /home/bruce/Git/smile/android''
That returns 'android: command not found'

I'm stumped.

[info] Loading global plugins from /home/bruce/.sbt/0.13/plugins
[info] Loading project definition from /home/bruce/Git/smile/project
java.lang.RuntimeException: set ANDROID_HOME or run 'android update project -p /home/bruce/Git/smile
/android'
        at scala.sys.package$.error(package.scala:27)
        at android.Plugin$$anonfun$allPluginSettings$67$$anonfun$apply$28.apply(rules.scala:350)
        at android.Plugin$$anonfun$allPluginSettings$67$$anonfun$apply$28.apply(rules.scala:350)
        at scala.Option.getOrElse(Option.scala:120)
        at android.Plugin$$anonfun$allPluginSettings$67.apply(rules.scala:350)
        at android.Plugin$$anonfun$allPluginSettings$67.apply(rules.scala:342)
        at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:54)
        at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:53)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:177)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.s
cala:67)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:76)
        at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:53)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:177)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.s
cala:67)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:76)

**Comment by darkoverlordofdata** [comment]
I removed the android build section from my build script, and now it works, at least for desktop.  That works for now. So the real issue seems to be that it doesn't see the  ANDROID_HOME environment variable. I'm running on Linux - elementary OS 0.3.2 Freya (64-bit) Built on Ubuntu 14.04.

**Comment by inkytonik** [comment]
As far as I know the sbt package is not doing anything special with environment variables.

Can you please try something for me? Open a non-sbt terminal in Atom using the Terminal Plus: New command (bound to Shift-Cmd-T on my Mac). You should get a shell prompt.

What happens if you run "echo $ANDROID_HOME" in that shell? Does the plain shell see the variable?

**Comment by darkoverlordofdata** [comment]
Ok, I just had to find the the android command line that the error message was referring to - you have to be in the folder $ANDROID_HOME/tools to run it. All does is update the android/local.properties to point to ANDROID_HOME.
Your plugin is working great.

**Comment by inkytonik** [comment]
Cool. Glad to hear it's working for you.
