### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by laughedelic** [inkytonik/atom-sbt#20]
1. I have two type of sbt prompts: one custom I set using the [sbt-prompt](https://github.com/agemooij/sbt-prompt) plugin, and another one which is set by the scala-play plugin. So I set the prompt pattern setting to `( »)|(\] \$)` (it either ends on `»` or on `$`).
2. Whichever pattern in this setting is first fails when I try to launch the plugin on a corresponding project.

**Atom**: 1.17.0-beta5 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [sbt](https://github.com/inkytonik/atom-sbt) package 0.10.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/laughedelic/github/sbt/lib/project.coffee:254

TypeError: Cannot read property 'length' of undefined
    at Project.module.exports.Project.outputToCmd (/packages/sbt/lib/project.coffee:254:26)
    at /packages/sbt/lib/project.coffee:238:20
    at Project.module.exports.Project.processData (/packages/sbt/lib/project.coffee:163:7)
    at /packages/sbt/lib/project.coffee:62:10
    at /Applications/Atom Beta.app/Contents/Resources/app/src/task.js:128:1
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at ChildProcess.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/src/task.js:80:1)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:45.1.0 project-folder:add (atom-pane.pane.active)
     -0:41.2.0 core:confirm (input.hidden-input)
     -0:41.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-syntax.theme-native-ui)
     -0:36.7.0 sbt:toggle-panel (input.hidden-input)
     -0:35.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-syntax.theme-native-ui)
     -0:03.3.0 sbt:compile (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
antialiased 0.1.0 
ariake-dark-syntax 0.1.3 
atom-busy-unifier-sb 1.0.3 
atom-csv-markdown 1.0.2 
atom-jade 0.3.0 
autoclose-html 0.23.0 
autocomplete-emojis 2.5.0 
autocomplete-haskell 0.7.2 
autocomplete-paths 1.0.5 
autoflow-diffable 0.5.0 
base16-syntax 1.8.0 
busy-signal 1.4.1 
cursor-history 0.10.1 
factoids 0.1.1 
file-icons 2.1.4 
file-types 0.5.5 
git-plus 7.8.0 
git-travel 0.1.4 
gl-light-syntax 2.2.0 
haskell-ghc-mod 1.19.9 
highlight-selected 0.13.1 
hyperclick 0.0.40 
ide-haskell 1.9.6 
intentions 1.1.2 
key-peek 0.2.12 
language-diff 0.7.0 
language-elm 1.5.0 
language-fish-shell 1.0.5 
language-gitignore 0.3.0 
language-haskell 1.12.1 
language-hocon 1.1.0 
language-latex 1.0.0 
language-pfm 0.82.0 
language-rdf 0.5.0 
language-scala 1.1.8 
language-sparql 0.3.0 
latex-completions 0.3.2 
line-diff-details 1.8.0 
linter 2.1.4 
linter-annotations 1.0.1 
linter-coffeescript 1.0.0 
linter-elm-make 0.23.2 
linter-markdown 4.0.1 
linter-ui-default 1.3.0 
markdown-folder 0.5.0 
markdown-preview-enhanced 0.12.1 
markdown-preview-plus 2.4.9 
markdown-table-formatter 2.9.0 
mathjax-wrapper 0.1.0 
merge-conflicts 1.4.4 
minimap 4.28.2 
native-ui 0.20.6 
package-manager-commands 2.0.3 
pdf-view 0.57.0 
pen-paper-coffee-syntax 0.14.9 
plain-simple 1.1.0 
platformio-ide-terminal 2.5.0 
plist-converter 0.1.6 
pretty-json 1.6.3 
preview-inline 1.4.7 
project-folder 1.3.0 
remember-folds 0.3.0 
sbt 0.10.0 
simple-align 0.2.0 
sort-lines 0.14.0 
sparql 0.0.0 
swackets 0.26.0 
tablr 1.8.3 
tabularize 0.2.5 
vim-mode-plus 0.91.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
xml-formatter 0.10.0 
```

**Comment by inkytonik** [comment]
I think the commit I just pushed fixes this. Will be in the next release.
