### ISSUE TITLE
Uncaught TypeError: Cannot read property 'statusBar' of undefined

### ISSUE THREAD

**Issue by rgladwell** [inkytonik/atom-sbt#5]
Running `alt-shift-O` in my Play application folder throw an exception straight away

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [sbt](https://github.com/inkytonik/atom-sbt) package, v0.1.0
### Stack Trace

Uncaught TypeError: Cannot read property 'statusBar' of undefined

```
At /Users/ricardo/.atom/packages/sbt/lib/sbt.coffee:137

TypeError: Cannot read property 'statusBar' of undefined
    at Object.module.exports.Sbt.notRunning (/Users/ricardo/.atom/packages/sbt/lib/sbt.coffee:137:12)
    at Object.module.exports.Sbt.togglePanel (/Users/ricardo/.atom/packages/sbt/lib/sbt.coffee:249:11)
    at atom-workspace.subscriptions.add.atom.commands.add.sbt:toggle-panel (/Users/ricardo/.atom/packages/sbt/lib/sbt.coffee:60:86)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Volumes/Storage/usr/local/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Volumes/Storage/usr/local/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Volumes/Storage/usr/local/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Volumes/Storage/usr/local/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Volumes/Storage/usr/local/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Volumes/Storage/usr/local/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -3:55.1.0 settings-view:open (atom-text-editor.editor.is-focused)
  2x -2:52.3.0 core:select-all (div.panels)
  2x -2:51.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:31.5.0 application:add-project-folder (atom-text-editor.editor.is-focused)
  3x -0:11.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:02.1.0 sbt:toggle-panel (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
sbt, v0.1.0

# Dev
No dev packages
```

**Comment by hohonuuli** [comment]
I just installed `atom-sbt` and I'm getting the same error (I have the same version/OS info as above).

**Comment by inkytonik** [comment]
Thanks for the reports. It appears to be that something is going wrong with the dependencies on other packages, so the required terminal-plus package is not there. I'll look into it.

**Comment by inkytonik** [comment]
I'm working on a fix relating to the installation of dependent Atom packages. This is an area that Atom doesn't support well out of the box and it's clear that my solution isn't working at the moment. I hope to have a version with a fix soon.

In the meantime, you should be able to use the sbt package after manually installing both the "linter" and "terminal-plus" packages.

**Comment by inkytonik** [comment]
I think d5e778b should make this problem go away. At least it all seems to work for me in a clean install of Atom 1.5.3. The dependent packages are now installed the first time you invoke the sbt package.

That commit is included in version 0.3.0 so if you could try that version and let me know what happens I'd appreciate it. It might be best to remove any mention of the sbt package from $HOME/.atom/packages and install 0.3.0 from scratch.

**Comment by hohonuuli** [comment]
@inkytonik I followed your instructions and dropped sbt from `$HOME/.atom/packages` then installed 0.3.0. Seems to be working great!! Thanks for your work, much appreciated!

**Comment by inkytonik** [comment]
Great @hohonuuli, thanks for testing. We'll call this one fixed then.
